In [1]:
import numpy as np

Cell to write down the input file for the script "numcom.py". 

One can set the following parameters:
1.   temperature: temperature of the simulation
2.   diffusione: diffusion coefficient of the simulation
3.   tstep: time step of the MD simulations used for the boundaries
4.   Nsim: number of MD simulations used to estimate the committor at the boundaries
5.   stepsim: number of maximum steps for each MD simulation
6.   xlimleft: left limit of the plot
7.   xlimright: left limit of the plot
8.   nxstep: number of grid point along the x-axis
10.  ylimup: upper limit of the plot
11.  nystep: number of grid point along the y-axis
12.  namefile: name of the file where to save the committor
13.  nameplot: name of the file where to save the plot of the committor
1. ncomm: number of committor guesses              
2. temperature: temperature of the simulation 
3. tstep: time step of the MD simulations used for the boundaries       
4. kratchet: constant of the ratchet force      
5. MDsteps: number of maximum steps for each MD simulation       
6. biassim: number of bias simulations in order to sample the trainsition region         
7. selfsteps: maximum number of self consistent iterations          
7. alpha: relaxation parameter of the self consistent procedure
8. threshold: threshold for the self consistent procedure
9. relaxation: if True, the biased probability distribution is relaxed at each self consistent step
10. relax 15: steps of MD simulation for the relaxation
11. xlimleft: left limit of the plots
12. xlimright: right limit of the plots
13. ylimdown: lower limit of the plots
14. ylimup: upper limit of the plots
15. delta: resolution of the plots
16. namecoeff: file where to save the evolution of the coefficients. If not provided, the coefficients are not saved
17. nametraj: name of the file where to save the plot of the trajectories used for the sampling. If not provided, the plot is not done
18. nameprob: name of the file where to save the plot of the sampled transition probability distribution. If not provided, the plot is not done

In [2]:
with open("input", "w") as f:
    print("""
ncomm 5              
temperature 1.0      
tstep 0.005           
kratchet 150       
MDsteps 15000        
biassim 2000         
selfsteps 15          
alpha 0.5    
threshold 0.001
relax 20
xlimleft -2.0
xlimright 2.0
ylimdown -1.5
ylimup 2.5
delta 0.025
namecoeff Coeff5.xyz
nameprob Prob5.pdf

        """,file=f)  

This cell runs directly the numcom.py script, but it can also be run from bash.

In [3]:
%%bash
python3.7 -W ignore varcom.py

Algorithm has started
Parameters loaded correctly
Cycle =  1
[0.33333333 0.33333333 0.33333333]
Cycle =  2
[[0.36343336 0.15602745 0.26452038]
 [0.15602745 0.88978356 0.16348811]
 [0.26452038 0.16348811 0.61035348]]
[0.62488098 0.20067182 0.1744472 ]
Cycle =  3
[[0.34894968 0.14658009 0.24793006]
 [0.14658009 0.18907199 0.15558296]
 [0.24793006 0.15558296 0.61923007]]
[0.16038455 0.81569193 0.02392352]
Cycle =  4
[[0.33360047 0.13965434 0.20882144]
 [0.13965434 0.15337643 0.14408649]
 [0.20882144 0.14408649 0.60793687]]
[0.06257677 0.92792594 0.00949729]
Cycle =  5
[[0.33924765 0.14217399 0.16906754]
 [0.14217399 0.12721523 0.12523247]
 [0.16906754 0.12523247 0.54240983]]
[4.05544180e-05 9.94480572e-01 5.47887330e-03]
Cycle =  6
[[0.34484271 0.14461256 0.16474958]
 [0.14461256 0.10043811 0.12204295]
 [0.16474958 0.12204295 0.52488508]]
[4.33375055e-06 9.99299372e-01 6.96294178e-04]
Cycle =  7
[[0.34715849 0.14644732 0.16395754]
 [0.14644732 0.12648447 0.12255848]
 [0.16395754 0.1225584